extend type Mutation {
  user_delete: DefaultResponse!
  user_deleteByEmail(email: String!): DefaultResponse!
}

type User {
  _id: ID!
  name: String!
  phone: String!
  email: String!
  address: String!
  isPinSet: Boolean!
}

type UserResponse {
  code: String!
  success: Boolean!
  data: User
  token: String
}

input UserFilter {
  username: String
}
